### PR TITLE
Kindling CI

### LINKED ISSUE #213: kindling: add CI tests
follow up issue to #210

### PR DESCRIPTION
**Pull request by marceline-cramer**
Closes #213.

### CODE REVIEW

**Comment by marceline-cramer** [comment]
Check annotations in Kindling aren't working, for some reason.

**Comment by marceline-cramer** [comment]
I think it must be because the `kindling_clippy` task is generating file annotations with paths relative to the `kindling` directory and not the root directory.

**Comment by marceline-cramer** [comment]
Trying to see if https://github.com/auguwu/clippy-action works but I need to rework the arguments. Putting this down for now.

**Comment by marceline-cramer** [comment]
rustfmt fails as expected but does not annotate the file successfully. Not sure if the hearth-rustfmt will annotate either, tbh.

**Comment by marceline-cramer** [comment]
Ok, the hearth-rustfmt doesn't annotate source files either. We could try to find a different action that supports annotation, or we could give up and read the CI log directly. What do you think @airidaceae?

**Comment by marceline-cramer** [comment]
This one is actively maintained and will either commit formatting fixes or request changes on the PR: https://github.com/mbrobbel/rustfmt-check

Auto-committing sounds convenient but... we know from experience with the depgraph CI that it can also be a pain.

**Comment by airidaceae** [comment]
both of those feel like overkill. the solution to rustfmt failing is to just run `cargo fmt` all we really need is something that will yell at us before we merge it. Most (all?) hearth devs already have some sort of auto format set up.

**Comment by airidaceae** [comment]
we never really need fine grained control over where fmt is failing imo. if we ever do, thats a larger problem with either CI or rustfmt as a whole

**Comment by marceline-cramer** [comment]
Alright, I'll undo the rustfmt breakers and then we're good to merge.

**Review by airidaceae — APPROVED** [review]

**Pull request merged**
