### PR TITLE
.github: add TODO bot workflow

### LINKED ISSUE #165: Add todo-issue action to CI workflow
Let's incorporate this action into our workflow: https://github.com/marketplace/actions/todo-issue

I for one definitely litter my code with TODO comments that a lot of the time never become fully-fledged issues, so this would be a big help for my workflow.

We'd want to update CONTRIBUTORS.md to notify contributors that it's in use.

### PR DESCRIPTION
**Pull request by marceline-cramer**
Closes #165.

I'm pretty nervous as to how this bot could potentially wreck our issue tracker, and it's hard to comprehend what the UX will actually look like in practice. I've implemented the workflow file for now but I'd like to sit on this for a while until we have that figured out.

I also think that all of the existing TODOs in the source code should be purged, and we shouldn't add any more until this PR is merged. #170 will remove a lot of those TODOs.

### CODE REVIEW

**Comment by marceline-cramer** [comment]
Just taking a look around bigger PRs, it's pretty clear that PR follow-up is really common. I think that this should definitely be done. If something goes unexpectedly wrong, we can always disable it. GitHub is luckily pretty good about making sure that everything is backed up.

**Comment by marceline-cramer** [comment]
Update: waiting for a few bigger PRs to get merged (#195 in particular) to reduce some temporary TODOs. At some point we're going to need to purge or update all the existing TODOs anyways before we can merge this, though.

**Comment by airidaceae** [comment]
may also want to keep in mind that we are changing over to forgejo in the near future and im not sure what this would look like there.

**Comment by marceline-cramer** [comment]
Another good point.

**Comment by airidaceae** [comment]
Honestly I think id be fine with manually adding the issues and cleaning up todo comments.

**Comment by marceline-cramer** [comment]
Yeah, I'm also reconsidering the value of this since we'll be migrating to Forgejo at some point too.

**Comment by airidaceae** [comment]
I really have no desire for this and it seems you dont either. Lets close it for now.

**Comment by marceline-cramer** [comment]
Agreed.

**Pull request closed without merging**
