### PR TITLE
Custom depgraph

### PR DESCRIPTION
**Pull request by marceline-cramer**
I made a new `hearth-depgraph` crate that generates a depgraph in `.dot` format just like the `cargo-depgraph` crate does, but it's much simpler, sets different attributes in the resulting `.dot` file, and most importantly, clusters together each crate based on its subdirectory in Hearth's repository.

I've also set up CI to use it instead of `cargo-depgraph`.

### CODE REVIEW

**Comment by airidaceae** [comment]
I really dont like that youre generating the file by hand with println statements. It feels like a hack. Have you looked into any crates for this? I found https://crates.io/crates/dot_graph with a bit of searching.

**Comment by airidaceae** [comment]
Im also not super happy with the final product either. I really liked the vertical structure of the old graph. It made the hierarchy much more clear to me and also ended up using less bendy lines, which this new graph has a lot of. I think that showing where each crate is from is useful but I'm not sure if its worth losing out on a clean and easy to understand graph.

**Comment by marceline-cramer** [comment]
This is what we get by naively switching it from left-to-right direction back to top-to-bottom.

depgraph

**Comment by airidaceae** [comment]
I think this could look good with some tweaking. Could you share your thoughts on why you like or dislike the current one?

**Comment by marceline-cramer** [comment]
> I think this could look good with some tweaking. Could you share your thoughts on why you like or dislike the current one?

The horizontal layout doesn't overlap the edges with the subgraph labels, and the lines are much cleaner since it's easier for lines to dodge around the height of each node rather than the width.

**Review by airidaceae — APPROVED** [review]

**Comment by marceline-cramer** [comment]
For reference, here's how the new depgraph will look:

image

**Pull request merged**
