### PR TITLE
readme: add shields

### PR DESCRIPTION
**Pull request by marceline-cramer**
Adds some useful shields from shields.io to our README, hopefully increasing the number of people that join our chats from Discord.

- [x] Discord
- [x] Matrix
- [x] license
- [x] Fedi
- [x] CI status
- [x] add icons?
- [x] better colors for shields
- [x] remove duplicated links?
- [x] better positioning within README?

### CODE REVIEW

**Comment by marceline-cramer** [comment]
@airidaceae could you please take a stab at doing the Matrix shield?

https://shields.io/badges/matrix

**Comment by airidaceae** [comment]
> @airidaceae could you please take a stab at doing the Matrix shield?
> 
> https://shields.io/badges/matrix

Can do!

**Comment by marceline-cramer** [comment]
Awesome, great work :D

**Comment by airidaceae** [comment]
shields.io only seems to support mastodon for fedi. It requires mastodon user IDs.

**Comment by airidaceae** [comment]
We could make our own by just fucking with the firefish API. I may give that a try at some point

**Comment by marceline-cramer** [comment]
Tokei, the service shields.io uses to count lines of code, has been broken for months, so I don't think we're going to be able to add a lines of code shield right now.

https://github.com/badges/shields/issues/9389

**Comment by airidaceae** [comment]
Thinking about an order for these. IMO the order of importance is
discord > license > build > matrix > fedi

I could also see value to grouping them by type
social: fedi, discord, matrix
code: license, build

Im afraid of bloating things too much, we may also want to remove some of the links that are below the badges or use them as a documentation directory instead.

**Comment by airidaceae** [comment]
For the ordering of the readme itself, maybe
Logo
badges
Name
Tagline
Links
Demo picture
body

**Comment by marceline-cramer** [comment]
> Thinking about an order for these. IMO the order of importance is discord > license > build > matrix > fedi
> 
> I could also see value to grouping them by type social: fedi, discord, matrix code: license, build
> 
> Im afraid of bloating things too much, we may also want to remove some of the links that are below the badges or use them as a documentation directory instead.

The Discord and Matrix links below the badges are redundant, so let's remove them for starters.

**Comment by marceline-cramer** [comment]
I also prefer grouping by social first. I don't like the idea of prioritizing Discord so much over Matrix.

**Comment by marceline-cramer** [comment]
> For the ordering of the readme itself, maybe Logo badges Name Tagline Links Demo picture body

I agree, I'll get on it

**Comment by marceline-cramer** [comment]
Actually @airidaceae, would you like to implement these changes yourself?

**Comment by airidaceae** [comment]
> I don't like the idea of prioritizing Discord so much over Matrix

My reasoning is that it slightly redundant to have 2 socials right next to each other (if we are ordering by priority) and most people use discord.

**Comment by airidaceae** [comment]
and yeah! I can implement them

**Comment by airidaceae** [comment]
not sure where the AGPL logo and Hearth logo copyright info should go

**Comment by airidaceae** [comment]
not sure why this is failing right now. I think its an issue with CI. Lets wait a bit and rerun later

**Comment by marceline-cramer** [comment]
Disroot's Forgejo instance is unavailable right now, so CI can't access `font-mud`.

**Review by airidaceae — APPROVED** [review]

**Pull request merged**
