### PR TITLE
font-mud: temporarily use git dep to fix msdfgen Mac CI

### PR DESCRIPTION
**Pull request by marceline-cramer**

### CODE REVIEW

**Comment by airidaceae** [comment]
krill issue :shrimp:

**Comment by marceline-cramer** [comment]
> krill issue 🦐

unbelievable.

**Review by airidaceae — APPROVED** [review]
Open an issue to switch back when upstream is fixed.

**Comment by marceline-cramer** [comment]
I should stop assuming that this works without running `cargo check --all-targets`.

**Comment by airidaceae** [comment]
> I should stop assuming that this works without running `cargo check --all-targets`.

probably :3

**Comment by airidaceae** [comment]
@marceline-cramer issue?

**Comment by marceline-cramer** [comment]
Sure thing.

**Pull request merged**
